#!/bin/bash
echo "Create Express.js Backend Project in: $(pwd)"
touch README.md
mkdir src
cd src
touch app.ts
mkdir db controllers models routers schemas middlewares
touch db/index.ts controllers/index.ts models/index.ts routers/index.ts schemas/index.ts middlewares/index.ts
cd ..
echo 'node_modules/
dist/
.env*' >.gitignore
echo 'MONGODB_URI=
#CLOUD_NAME=
#API_KEY=
#API_SECRET=

## JWT
ACCESS_TOKEN_TTL=900  ## 15 minutes
REFRESH_TOKEN_TTL=1209600 ##14 days
JWT_ISSUER=AUIT25' > .env
node -e "console.log('ACCESS_JWT_SECRET='+require('crypto').randomBytes(32).toString('hex'))">> .env
node -e "console.log('REFRESH_JWT_SECRET='+require('crypto').randomBytes(32).toString('hex'))">> .env
echo 'import mongoose from "mongoose";

try {
  await mongoose.connect(process.env.MONGODB_URI!, {
    dbName: process.env.DB_NAME,
  });
  console.log("\x1b[35m✅ MongoDB connected via Mongoose\x1b[0m");
} catch (error) {
  console.error("❌ MongoDB connection error:", error);
  process.exit(1);
}' > src/db/index.ts
echo '{
  "name": "new_project",
  "version": "1.0.0",
  "description": "",
  "main": "dist/app.js",
  "type": "module",
  "imports": {
    "#db": {
      "development": "src/db/index.ts",
      "default": "dist/db/index.js"
    },
    "#utils": {
      "development": "src/utils/index.ts",
      "default": "dist/utils/index.js"
    },
    "#models": {
      "development": "src/models/index.ts",
      "default": "dist/models/index.js"
    },
    "#schemas": {
      "development": "src/schemas/index.ts",
      "default": "dist/schemas/index.js"
    },
    "#routers": {
      "development": "src/routers/index.ts",
      "default": "dist/routers/index.js"
    },
    "#controllers": {
      "development": "src/controllers/index.ts",
      "default": "dist/controllers/index.js"
    },
    "#middlewares": {
      "development": "src/middlewares/index.ts",
      "default": "dist/middlewares/index.js"
    }
  },
  "scripts": {
    "dev": " node --watch --env-file=.env --conditions development src/app.ts",
    "prebuild": "rm -rf dist",
    "build": "tsc",
    "prestart": "npm run build",
    "start": "node --env-file=.env dist/app.js"
  },
  "keywords": [],
  "author": "",
  "license": ""
}' > package.json
echo '{
  "compilerOptions": {
    /* Base Options: */
    "esModuleInterop": true, // Enables default imports from CommonJS modules
    "lib": ["ESNext"], // Includes modern ES features in the type system
    "target": "ESNext", // Sets the JavaScript version output
    "skipLibCheck": true, // Skips type checking of declaration files (*.d.ts)
    "allowJs": true, // Allows JavaScript files in the project
    "resolveJsonModule": true, // Allows importing JSON modules
    "moduleDetection": "force", // Treats all files as modules regardless of import/export
    "isolatedModules": true, // Ensures each file can be transpiled independently
    "verbatimModuleSyntax": true, // Keeps import/export syntax as-is for Node.js
    /* Strictness */
    "strict": true, // Enables all strict type-checking options
    "noUncheckedIndexedAccess": true, // Adds 'undefined' to object access via index if type not declared
    "noImplicitOverride": true, // Requires 'override' keyword when overriding methods
    /* Node Options*/
    "allowImportingTsExtensions": true, // Allows importing files with .ts extensions
    "rewriteRelativeImportExtensions": true, // Rewrites relative imports with correct extensions
    "module": "preserve", // Preserves ES module syntax (important for native ESM)
    "noEmit": false, // Enables output generation
    "outDir": "dist", // Output directory for compiled JavaScript
    /* Paths */
    "baseUrl": "./src", // Base path for module resolution
    "paths": {
      "#*": ["*"] // Defines internal path aliases with '#' to avoid conflict with '@'
    }
  },
  "include": ["src"] // Files to include in compilation
}' > tsconfig.json
echo 'import "#db";
import express from "express";
import { errorHandler } from "#middlewares";
import cookieParser from "cookie-parser";

const app = express();
const port = 3000;

//Middleware
app.use(express.json());
app.use(cookieParser());

//Routes

//Error Handling
app.use(errorHandler);

//Start Server
app.listen(port, () =>
  console.log(
    `🐦‍🔥 \x1b[34mServer is running on http://localhost:${port}\x1b[0m 🐦‍🔥`
  )
);' > src/app.ts
echo 'import type { ErrorRequestHandler } from "express";

const errorHandler: ErrorRequestHandler = (err, req, res, next) => {
  process.env.NODE_ENV !== "production" &&
    console.error(`\x1b[31m${err.stack}\x1b[0m`);

  if (err instanceof Error) {
    if (err.cause) {
      const cause = err.cause as { status: number };

      res.status(cause.status).json({ message: err.message });
      return;
    }

    res.status(500).json({ message: err.message });
    return;
  }

  res.status(500).json({ message: "Internal server error" });
  return;
};

export default errorHandler;' > src/middlewares/errorHandler.ts
echo 'import type { RequestHandler } from "express";
import type { ZodObject } from "zod/v4";

const validateBodyZod =
  (zodSchema: ZodObject): RequestHandler =>
  (req, res, next) => {
    const parsed = zodSchema.safeParse(req.body);

    if (!parsed.success) {
      const issues = parsed.error?.issues.map((issue) => ({
        path: issue.path.join(),
        message: issue.message,
      }));

      return res.status(400).json({
        message: "Validation failed",
        issues,
      });
    }

    req.body = parsed.data;
    next();
  };

export default validateBodyZod;' > src/middlewares/validateBodyZod.ts
echo 'export { default as errorHandler } from "./errorHandler.ts";
export { default as validateBodyZod } from "./validateBodyZod.ts";' > src/middlewares/index.ts
npm i express mongoose zod bcrypt cookie-parser jsonwebtoken
npm i -g typescript
npm i -D @types/typescript @types/node @types/mongoose @types/express @types/bcrypt @types/cookie-parser @types/jsonwebtoken
read -p "Press [Enter] to exit..."
